### ISSUE TITLE
代理后，截图为什么只有代理的图片，无法截取其他的页面元素

### ISSUE THREAD

**Issue by myGITHUBdata** [brcontainer/html2canvas-php-proxy#32]
点击截图后，返回正常的代理图片，但是无法创建canvas，并且没有页面其他的元素，只是返回了代理图片

**Comment by brcontainer** [comment]
Hi @myGITHUBdata

In order to be able to understand the problem, it is necessary to report:

1.  Log (see details in https://github.com/brcontainer/html2canvas-php-proxy#using-web-console)

1.  Tell me which version of html2canvas you use (I'm not talking about the proxy but the lib developed by Joao)

1.  "Web Page" where failure occurs

> **IMPORTANT NOTE:** The html2canvas only works on HTTP, FILE protocol is not supported.
